# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_core', [dirname(__file__)])
        except ImportError:
            import _core
            return _core
        if fp is not None:
            try:
                _mod = imp.load_module('_core', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _core = swig_import_helper()
    del swig_import_helper
else:
    import _core
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class core(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, core, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, core, name)
    __repr__ = _swig_repr
    def init(self, *args): return _core.core_init(self, *args)
    def uninit(self): return _core.core_uninit(self)
    def BeginFrame(self): return _core.core_BeginFrame(self)
    def update(self): return _core.core_update(self)
    def EndFrame(self): return _core.core_EndFrame(self)
    def BeginVisualFrame(self): return _core.core_BeginVisualFrame(self)
    def UpdateVisual(self): return _core.core_UpdateVisual(self)
    def EndVisualFrame(self): return _core.core_EndVisualFrame(self)
    def BeginLogicalFrame(self): return _core.core_BeginLogicalFrame(self)
    def UpdateLogical(self): return _core.core_UpdateLogical(self)
    def EndLogicalFrame(self): return _core.core_EndLogicalFrame(self)
    def __init__(self): 
        this = _core.new_core()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _core.delete_core
    __del__ = lambda self : None;
core_swigregister = _core.core_swigregister
core_swigregister(core)



