# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_basis', [dirname(__file__)])
        except ImportError:
            import _basis
            return _basis
        if fp is not None:
            try:
                _mod = imp.load_module('_basis', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _basis = swig_import_helper()
    del swig_import_helper
else:
    import _basis
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


axis_x = _basis.axis_x
axis_y = _basis.axis_y
axis_z = _basis.axis_z
class point(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, point, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, point, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _basis.point_x_set
    __swig_getmethods__["x"] = _basis.point_x_get
    if _newclass:x = _swig_property(_basis.point_x_get, _basis.point_x_set)
    __swig_setmethods__["y"] = _basis.point_y_set
    __swig_getmethods__["y"] = _basis.point_y_get
    if _newclass:y = _swig_property(_basis.point_y_get, _basis.point_y_set)
    def __init__(self): 
        this = _basis.new_point()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _basis.delete_point
    __del__ = lambda self : None;
point_swigregister = _basis.point_swigregister
point_swigregister(point)

class vector2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector2, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _basis.new_vector2(*args)
        try: self.this.append(this)
        except: self.this = this
    def __eq__(self, *args): return _basis.vector2___eq__(self, *args)
    def _assign(self, *args): return _basis.vector2__assign(self, *args)
    def _float(self): return _basis.vector2__float(self)
    __swig_setmethods__["x"] = _basis.vector2_x_set
    __swig_getmethods__["x"] = _basis.vector2_x_get
    if _newclass:x = _swig_property(_basis.vector2_x_get, _basis.vector2_x_set)
    __swig_setmethods__["y"] = _basis.vector2_y_set
    __swig_getmethods__["y"] = _basis.vector2_y_get
    if _newclass:y = _swig_property(_basis.vector2_y_get, _basis.vector2_y_set)
    __swig_destroy__ = _basis.delete_vector2
    __del__ = lambda self : None;
vector2_swigregister = _basis.vector2_swigregister
vector2_swigregister(vector2)

class vector3(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector3, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _basis.new_vector3(*args)
        try: self.this.append(this)
        except: self.this = this
    def __add__(self, *args): return _basis.vector3___add__(self, *args)
    def __sub__(self, *args): return _basis.vector3___sub__(self, *args)
    def normalize(self): return _basis.vector3_normalize(self)
    def __eq__(self, *args): return _basis.vector3___eq__(self, *args)
    def _assign(self, *args): return _basis.vector3__assign(self, *args)
    def length(self): return _basis.vector3_length(self)
    def _float(self): return _basis.vector3__float(self)
    __swig_setmethods__["x"] = _basis.vector3_x_set
    __swig_getmethods__["x"] = _basis.vector3_x_get
    if _newclass:x = _swig_property(_basis.vector3_x_get, _basis.vector3_x_set)
    __swig_setmethods__["y"] = _basis.vector3_y_set
    __swig_getmethods__["y"] = _basis.vector3_y_get
    if _newclass:y = _swig_property(_basis.vector3_y_get, _basis.vector3_y_set)
    __swig_setmethods__["z"] = _basis.vector3_z_set
    __swig_getmethods__["z"] = _basis.vector3_z_get
    if _newclass:z = _swig_property(_basis.vector3_z_get, _basis.vector3_z_set)
    __swig_destroy__ = _basis.delete_vector3
    __del__ = lambda self : None;
vector3_swigregister = _basis.vector3_swigregister
vector3_swigregister(vector3)

class vector4(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector4, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector4, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _basis.new_vector4(*args)
        try: self.this.append(this)
        except: self.this = this
    def _assign(self, *args): return _basis.vector4__assign(self, *args)
    def _vector3(self): return _basis.vector4__vector3(self)
    def _float(self): return _basis.vector4__float(self)
    def length(self): return _basis.vector4_length(self)
    __swig_setmethods__["x"] = _basis.vector4_x_set
    __swig_getmethods__["x"] = _basis.vector4_x_get
    if _newclass:x = _swig_property(_basis.vector4_x_get, _basis.vector4_x_set)
    __swig_setmethods__["y"] = _basis.vector4_y_set
    __swig_getmethods__["y"] = _basis.vector4_y_get
    if _newclass:y = _swig_property(_basis.vector4_y_get, _basis.vector4_y_set)
    __swig_setmethods__["z"] = _basis.vector4_z_set
    __swig_getmethods__["z"] = _basis.vector4_z_get
    if _newclass:z = _swig_property(_basis.vector4_z_get, _basis.vector4_z_set)
    __swig_setmethods__["w"] = _basis.vector4_w_set
    __swig_getmethods__["w"] = _basis.vector4_w_get
    if _newclass:w = _swig_property(_basis.vector4_w_get, _basis.vector4_w_set)
    __swig_destroy__ = _basis.delete_vector4
    __del__ = lambda self : None;
vector4_swigregister = _basis.vector4_swigregister
vector4_swigregister(vector4)

class Edge2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Edge2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Edge2, name)
    __repr__ = _swig_repr
    __swig_setmethods__["p"] = _basis.Edge2_p_set
    __swig_getmethods__["p"] = _basis.Edge2_p_get
    if _newclass:p = _swig_property(_basis.Edge2_p_get, _basis.Edge2_p_set)
    def __init__(self): 
        this = _basis.new_Edge2()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _basis.delete_Edge2
    __del__ = lambda self : None;
Edge2_swigregister = _basis.Edge2_swigregister
Edge2_swigregister(Edge2)

class Edge3(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Edge3, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Edge3, name)
    __repr__ = _swig_repr
    __swig_setmethods__["p"] = _basis.Edge3_p_set
    __swig_getmethods__["p"] = _basis.Edge3_p_get
    if _newclass:p = _swig_property(_basis.Edge3_p_get, _basis.Edge3_p_set)
    def __init__(self): 
        this = _basis.new_Edge3()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _basis.delete_Edge3
    __del__ = lambda self : None;
Edge3_swigregister = _basis.Edge3_swigregister
Edge3_swigregister(Edge3)


def multiply_matrix(*args):
  return _basis.multiply_matrix(*args)
multiply_matrix = _basis.multiply_matrix
class matrix44(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, matrix44, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, matrix44, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _basis.new_matrix44(*args)
        try: self.this.append(this)
        except: self.this = this
    def __mul__(self, *args): return _basis.matrix44___mul__(self, *args)
    def set_identity(self): return _basis.matrix44_set_identity(self)
    def get_axis(self, *args): return _basis.matrix44_get_axis(self, *args)
    def _float(self): return _basis.matrix44__float(self)
    def _kfloat(self): return _basis.matrix44__kfloat(self)
    __swig_setmethods__["m"] = _basis.matrix44_m_set
    __swig_getmethods__["m"] = _basis.matrix44_m_get
    if _newclass:m = _swig_property(_basis.matrix44_m_get, _basis.matrix44_m_set)
    __swig_destroy__ = _basis.delete_matrix44
    __del__ = lambda self : None;
matrix44_swigregister = _basis.matrix44_swigregister
matrix44_swigregister(matrix44)

class vector_argb(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vector_argb, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vector_argb, name)
    __repr__ = _swig_repr
    __swig_setmethods__["a"] = _basis.vector_argb_a_set
    __swig_getmethods__["a"] = _basis.vector_argb_a_get
    if _newclass:a = _swig_property(_basis.vector_argb_a_get, _basis.vector_argb_a_set)
    __swig_setmethods__["r"] = _basis.vector_argb_r_set
    __swig_getmethods__["r"] = _basis.vector_argb_r_get
    if _newclass:r = _swig_property(_basis.vector_argb_r_get, _basis.vector_argb_r_set)
    __swig_setmethods__["g"] = _basis.vector_argb_g_set
    __swig_getmethods__["g"] = _basis.vector_argb_g_get
    if _newclass:g = _swig_property(_basis.vector_argb_g_get, _basis.vector_argb_g_set)
    __swig_setmethods__["b"] = _basis.vector_argb_b_set
    __swig_getmethods__["b"] = _basis.vector_argb_b_get
    if _newclass:b = _swig_property(_basis.vector_argb_b_get, _basis.vector_argb_b_set)
    def __init__(self): 
        this = _basis.new_vector_argb()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _basis.delete_vector_argb
    __del__ = lambda self : None;
vector_argb_swigregister = _basis.vector_argb_swigregister
vector_argb_swigregister(vector_argb)

class color_inner_data(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, color_inner_data, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, color_inner_data, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ARGB"] = _basis.color_inner_data_ARGB_set
    __swig_getmethods__["ARGB"] = _basis.color_inner_data_ARGB_get
    if _newclass:ARGB = _swig_property(_basis.color_inner_data_ARGB_get, _basis.color_inner_data_ARGB_set)
    __swig_setmethods__["vargb"] = _basis.color_inner_data_vargb_set
    __swig_getmethods__["vargb"] = _basis.color_inner_data_vargb_get
    if _newclass:vargb = _swig_property(_basis.color_inner_data_vargb_get, _basis.color_inner_data_vargb_set)
    def __init__(self): 
        this = _basis.new_color_inner_data()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _basis.delete_color_inner_data
    __del__ = lambda self : None;
color_inner_data_swigregister = _basis.color_inner_data_swigregister
color_inner_data_swigregister(color_inner_data)

class Color(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Color, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Color, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _basis.new_Color(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["m"] = _basis.Color_m_set
    __swig_getmethods__["m"] = _basis.Color_m_get
    if _newclass:m = _swig_property(_basis.Color_m_get, _basis.Color_m_set)
    def _assign(self, *args): return _basis.Color__assign(self, *args)
    def _DWORD(self): return _basis.Color__DWORD(self)
    def ToRGB(self): return _basis.Color_ToRGB(self)
    __swig_destroy__ = _basis.delete_Color
    __del__ = lambda self : None;
Color_swigregister = _basis.Color_swigregister
Color_swigregister(Color)


def vec_normalize(*args):
  return _basis.vec_normalize(*args)
vec_normalize = _basis.vec_normalize

def vec_cross(*args):
  return _basis.vec_cross(*args)
vec_cross = _basis.vec_cross

def vec_dot(*args):
  return _basis.vec_dot(*args)
vec_dot = _basis.vec_dot

def build_matrix_perspective_fov_lh(*args):
  return _basis.build_matrix_perspective_fov_lh(*args)
build_matrix_perspective_fov_lh = _basis.build_matrix_perspective_fov_lh

def build_matrix_lookat_lh(*args):
  return _basis.build_matrix_lookat_lh(*args)
build_matrix_lookat_lh = _basis.build_matrix_lookat_lh

def build_matrix_rotation_axis(*args):
  return _basis.build_matrix_rotation_axis(*args)
build_matrix_rotation_axis = _basis.build_matrix_rotation_axis

def build_matrix_trans_rot_scale(*args):
  return _basis.build_matrix_trans_rot_scale(*args)
build_matrix_trans_rot_scale = _basis.build_matrix_trans_rot_scale

def arctan2radian(*args):
  return _basis.arctan2radian(*args)
arctan2radian = _basis.arctan2radian


def vec_transform(*args):
  return _basis.vec_transform(*args)
vec_transform = _basis.vec_transform

